name: mpcproject
dependencies:
  - pip=18.1
  - pandas=1.1.3
  - seaborn=0.11.0
  - scipy=1.5.2
  - matplotlib=3.3.2
  - pip:
      - brokenaxes==0.4.2
      - comut==0.0.3
      - matplotlib-venn==0.11.6
      - palettable==3.3.0
